site_name: Math
site_description: Deeply reinforcing math
site_author: Alexander Lindholm
site_url: https://math.alexanderlindholm.net
repo_url: https://github.com/Alex0424/math

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.math

markdown_extensions:
  - admonition
  - toc:
      permalink: true

  - pymdownx.arithmatex:
      generic: true

  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:mermaid2.fence_mermaid_custom"

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  
  - Aritmetik & Algebra:
    - MGN: arithmetic_algebra/mgn.md
    - Algebra Basics: arithmetic_algebra/algebra_basics.md
    - Numbers: arithmetic_algebra/tal.md
    - Sju räknesätten: arithmetic_algebra/sju_räknesätten.md
    - Prioriterings-reglerna: arithmetic_algebra/prioriterings_reglerna.md

  - Potenser:
    - potenslagar: potenser/potenslagar.md
    - potensekvationer: potenser/potensekvationer.md
